{
 "title": "GNSS NMEA Demo",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "NMEA Messages",
   "type": "graph",
   "gridPos": { "h": 11, "w": 15, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rate(nmea_total[5m])", "legendFormat": "{{message_type}}" }
   ]
  },
  {
   "title": "Horizontal Accuracy",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "nmea_accuracy_horizontal", "legendFormat": " " }
   ]
  },
  {
   "title": "Vertical Accuracy",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nmea_accuracy_vertical", "legendFormat": " " }
   ]
  },
  {
   "title": "Message Rate",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "sum(rate(nmea_total[10m]))" }
   ]
  },
  {
   "title": "Satelllites",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nmea_satellites" }
   ]
  },
  {
   "title": "Spring Integration Channels",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 4, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(spring_integration_receive_total[5m])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Status",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "nmea_status" }
   ]
  }
 ]
}